# Generated by Django 5.0.4 on 2024-05-02 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("level", models.IntegerField()),
                ("succession_plan_needed", models.BooleanField()),
                ("date_audited", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="SuccessionPlan",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("notes", models.CharField(max_length=255)),
                ("date_added", models.DateField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="succession_plans.employee",
                    ),
                ),
            ],
        ),
    ]
